version: 0.2

env:
  variables:
    SAGEMAKER_PIPELINE_NAME: sagemaker-mlops-fraud-pipeline
    
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install awscliv2
      - pip install boto3
      - pip install sagemaker
  
  build:
    commands:
      - echo "Start SageMaker Pipeline"
      - export PYTHONUNBUFFERED=TRUE
      - |
        python3 create-mode-endconfig-end.py
      - echo "Exection of the SageMaker Pipeline completed."
